<a href="https://colab.research.google.com/github/Avonna/Avona/blob/main/IntroToPyTorch_task.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Знакомство с PyTorch

Сейчас мы познакомимся с библиотекой *PyTorch*. Он очень похож на *NumPy*, и сейчас вы в этом убедитесь!

А почему именно *PyTorch*? Почитать можно [здесь](https://habr.com/ru/post/334380/).

## Вспоминаем *NumPy* и сравниваем операции в *PyTorch*

Мы можем создавать матрицы, перемножать их, складывать, транспонировать и в целом совершать любые матричные операции

In [1]:
import numpy as np 

import torch
import torchvision

import torch.nn as nn
import torch.nn.functional as F

import matplotlib.pyplot as plt

In [2]:
np.random.seed(42)

a = np.random.rand(5, 3) # создали случайную матрицу 
a

array([[0.37454012, 0.95071431, 0.73199394],
       [0.59865848, 0.15601864, 0.15599452],
       [0.05808361, 0.86617615, 0.60111501],
       [0.70807258, 0.02058449, 0.96990985],
       [0.83244264, 0.21233911, 0.18182497]])

In [3]:
print("Проверили размеры : %s\n" % (a.shape,))

Проверили размеры : (5, 3)



In [4]:
print("Добавили 5 :\n%s\n" % (a + 5))

Добавили 5 :
[[5.37454012 5.95071431 5.73199394]
 [5.59865848 5.15601864 5.15599452]
 [5.05808361 5.86617615 5.60111501]
 [5.70807258 5.02058449 5.96990985]
 [5.83244264 5.21233911 5.18182497]]



## Задание

Умножьте матрицу `а` на транспонированную матрицу `а`.  

Чему равен самый первый элемент результата?  
Ответ округлите до сотых.

In [6]:
# your code here
print(np.dot(a, a.T))

[[1.57995312 0.48673782 1.28525324 0.9947397  0.64675177]
 [0.48673782 0.40706809 0.26368252 0.57840584 0.55984141]
 [1.28525324 0.26368252 1.11497408 0.64198458 0.34157207]
 [0.9947397  0.57840584 0.64198458 1.44251562 0.77015453]
 [0.64675177 0.55984141 0.34157207 0.77015453 0.77110897]]


In [7]:
print("Среднее по колонкам :\n%s\n" % (a.mean(axis=-1)))

Среднее по колонкам :
[0.68574946 0.30355721 0.50845826 0.56618897 0.40886891]



In [8]:
print("Изменили размеры :\n%s\n" % (a.reshape(3, 5).shape,))

Изменили размеры :
(3, 5)



## Задание

При помощи *NumPy* посчитайте сумму квадратов натуральных чисел от 1 до 10000.

In [19]:
# your code here
b = np.arange(start=1, stop=10001, step=1)
#b = b**2
ssq = np.sum(b**2)
ssq

333383335000

Аналогичные операции в *PyTorch* выглядят следующим образом, синтаксис отличается, но совсем немного:

In [9]:
x = torch.rand(5, 3)
x

tensor([[0.2196, 0.9661, 0.4488],
        [0.2821, 0.5516, 0.7227],
        [0.9061, 0.4496, 0.4312],
        [0.1586, 0.8677, 0.2409],
        [0.2322, 0.9104, 0.1414]])

In [10]:
print("Проверили размеры : %s\n" % (x.shape,))

Проверили размеры : torch.Size([5, 3])



In [11]:
print("Добавили 5 :\n%s\n" % (x + 5))

Добавили 5 :
tensor([[5.2196, 5.9661, 5.4488],
        [5.2821, 5.5516, 5.7227],
        [5.9061, 5.4496, 5.4312],
        [5.1586, 5.8677, 5.2409],
        [5.2322, 5.9104, 5.1414]])



In [12]:
print("X*X^T  (1):\n%s\n" % (torch.matmul(x, x.transpose(1, 0))))
print("X*X^T  (2):\n%s\n" % (x.mm(x.t())))

X*X^T  (1):
tensor([[1.1831, 0.9192, 0.8269, 0.9813, 0.9941],
        [0.9192, 0.9061, 0.8152, 0.6975, 0.6699],
        [0.8269, 0.8152, 1.2091, 0.6377, 0.6807],
        [0.9813, 0.6975, 0.6377, 0.8361, 0.8609],
        [0.9941, 0.6699, 0.6807, 0.8609, 0.9028]])

X*X^T  (2):
tensor([[1.1831, 0.9192, 0.8269, 0.9813, 0.9941],
        [0.9192, 0.9061, 0.8152, 0.6975, 0.6699],
        [0.8269, 0.8152, 1.2091, 0.6377, 0.6807],
        [0.9813, 0.6975, 0.6377, 0.8361, 0.8609],
        [0.9941, 0.6699, 0.6807, 0.8609, 0.9028]])



In [13]:
print("Среднее по колонкам :\n%s\n" % (x.mean(dim=-1)))

Среднее по колонкам :
tensor([0.5448, 0.5188, 0.5956, 0.4224, 0.4280])



In [14]:
print("Изменили размеры :\n%s\n" % (x.view([3, 5]).shape,))
print("Изменили размеры :\n%s\n" % (x.view_as(x.t()).shape,))

Изменили размеры :
torch.Size([3, 5])

Изменили размеры :
torch.Size([3, 5])



Небольшой пример того, как меняются операции:

* `x.reshape([1,2,8]) -> x.view(1,2,8)`

* `x.sum(axis=-1) -> x.sum(dim=-1)`

* `x.astype('int64') -> x.type(torch.LongTensor)`

Для помощи вам есть [таблица](https://github.com/torch/torch7/wiki/Torch-for-Numpy-users), которая поможет вам найти аналог операции в *NumPy*.


При помощи *PyTorch* посчитаем сумму квадратов натуральных чисел от 1 до 10000.

In [20]:
torch.sum(torch.range(1, 10000) ** 2)

<ipython-input-20-b9d129fd8adb>:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.sum(torch.range(1, 10000) ** 2)


tensor(3.3338e+11)

Создаем тензоры в *PyTorch* и снова изучаем базовые операции

In [21]:
x = torch.empty(5, 3) # пустой тензор
print(x)

tensor([[6.7403e-34, 4.5664e-41, 6.7403e-34],
        [4.5664e-41, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00],
        [1.4013e-45, 1.5414e-44, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.1351e-43]])


In [22]:
x = torch.rand(5, 3) # тензор со случайными числами
print(x)

tensor([[0.1980, 0.6171, 0.9252],
        [0.9059, 0.1676, 0.0296],
        [0.0750, 0.8905, 0.4857],
        [0.4778, 0.6977, 0.7217],
        [0.1951, 0.7770, 0.8756]])


In [23]:
x = torch.zeros(5, 3, dtype=torch.long) # тензор с нулями и указанием типов чисел
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [25]:
x = torch.tensor([5.5, 3]) # конструируем тензор из питоновского листа
print(x)

tensor([5.5000, 3.0000])


In [26]:
x = x.new_ones(5, 3, dtype=torch.double) # используем уже созданный тензор для создания тензора из единичек
print(x, x.size()) 

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64) torch.Size([5, 3])


In [27]:
x = torch.randn_like(x, dtype=torch.float) # создаем матрицу с размерами как у x
print(x, x.size())

tensor([[-1.2284,  0.5294,  1.2211],
        [ 0.1511, -0.3319, -0.4785],
        [-0.2631, -0.1786, -1.1859],
        [-0.8860, -0.7150,  0.1280],
        [-0.1603, -2.2161, -0.6858]]) torch.Size([5, 3])


## Задание

Сгенерируйте два тензора: `x` и `y` размера 5 на 3 со случайными числами.
Вычислите сумму тензоров `x` и `y`.

В ответе напишите значение первой координаты в полученной суммы, округленной до сотых.

In [31]:
torch.manual_seed(42)
x = torch.rand(5, 3) # тензор со случайными числами
y = torch.rand(5, 3) # тензор со случайными числами
#print(x)
torch.sum(x)
# your code here

tensor(9.9613)

In [32]:
print(x * y) # поэлементное умножение

tensor([[1.3117, 1.8004, 0.9568],
        [1.2259, 1.0179, 0.8705],
        [0.6979, 1.0906, 1.7725],
        [0.2385, 1.2041, 0.9524],
        [1.0688, 1.1149, 0.7473]])


## Задание

Умножьте матрицу `x` на транспонированную матрицу `y`.

В ответ напишите последний элемент (правый нижний) полученной матрицы.  
Ответ округлите до сотых.

In [33]:
# your code here
torch.mm(x, y.t())

tensor([[1.4088, 0.9125, 0.9795, 0.4769, 0.6789],
        [1.1025, 0.6627, 1.0391, 0.4219, 0.4086],
        [1.3528, 0.8200, 1.1313, 0.5785, 0.4912],
        [1.2254, 0.7820, 0.8300, 0.4789, 0.5416],
        [1.3013, 0.7878, 1.1686, 0.5105, 0.4885]])

In [ ]:
print(x.unsqueeze(0).shape) # добавили измерение в начало, аналог броадкастинга 

torch.Size([1, 5, 3])


In [ ]:
print(x.unsqueeze(0).squeeze(0).shape) # убрали измерение в начале, аналог броадкастинга 

torch.Size([5, 3])


In [ ]:
a = torch.rand((1,3))
a

tensor([[0.8823, 0.9150, 0.3829]])

In [ ]:
a.squeeze(0)

tensor([0.8823, 0.9150, 0.3829])

Мы также можем делать обычные срезы и переводить матрицы назад в *NumPy*:

In [ ]:
a = np.ones((3, 5))
x = torch.ones((3, 5))
print(np.allclose(x.numpy(), a))
print(np.allclose(x.numpy()[:, 1], a[:, 1]))

True
True


In [ ]:
a = np.array([1,2,3,4])
b = np.array([[5],[6],[7],[8]])

a.shape, b.shape

((4,), (4, 1))

In [ ]:
a @ b

array([70])

In [ ]:
b @ a

ValueError: ignored